---
- name: Ensure Apache is installed and running
  hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
  handlers:
    - name: Start Apache
      service:
        name: apache2
        state: started
